
library(methods)
library(demest)

struc_zero_popn <- Values(array(c(1, 1, 0, 1, 0, 1, 0, 1),
                                dim = c(2, 4),
                                dimnames = list(age = c("0-14", "15+"),
                                                status = c("Single", "Married", "Divorced", "Widowed"))))
population <- Model(population ~ Poisson(mean ~ (age + sex + status + time)^2 + age:sex:status,
                                         useExpose = FALSE,
                                         structuralZeros = struc_zero_popn),
                    age ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                              trend = Trend(scale = HalfT(scale = 0.1)),
                              damp = NULL,
                              error = Error(scale = HalfT(scale = 0.1))),
                    sex ~ Exch(error = Error(scale = HalfT(scale = 0.1))),
                    status ~ Exch(),
                    time ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                               trend = Trend(scale = HalfT(scale = 0.1)),
                               damp = NULL,
                               error = Error(scale = HalfT(scale = 0.1))),
                    age:sex ~ Exch(error = Error(scale = HalfT(scale = 0.1))),
                    age:status ~ Exch(),
                    age:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                   trend = Trend(scale = HalfT(scale = 0.05)),
                                   damp = NULL,
                                   error = Error(scale = HalfT(scale = 0.05))),
                    sex:status ~ Exch(error = Error(scale = HalfT(scale = 0.1))),
                    sex:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                   trend = NULL,
                                   damp = NULL,
                                   error = Error(scale = HalfT(scale = 0.05))),
                    status:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                      trend = Trend(scale = HalfT(scale = 0.05)),
                                      damp = NULL,
                                      error = Error(scale = HalfT(scale = 0.05))),
                    age:sex:status ~ Exch(),
                    jump = 0.024)

struc_zero_births <- Values(array(c(0, 1, 0, 0,
                                    0, 0, 0, 0,
                                    0, 0, 0, 0,
                                    0, 0, 0, 0),
                                  dim = c(4, 4),
                                  dimnames = list(status_parent = c("Single", "Married", "Divorced", "Widowed"),
                                                  status_child = c("Single", "Married", "Divorced", "Widowed"))))
births <- Model(births ~ Poisson(mean ~ age * time + sex,
                                 structuralZeros = struc_zero_births),
                age ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                          trend = Trend(scale = HalfT(scale = 0.1)),
                          damp = NULL,
                          error = Error(scale = HalfT(scale = 0.1))),
                time ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                           trend = Trend(scale = HalfT(scale = 0.1)),
                           damp = NULL,
                           error = Error(scale = HalfT(scale = 0.1))),
                age:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                               trend = Trend(scale = HalfT(scale = 0.05)),
                               damp = NULL,
                               error = Error(scale = HalfT(scale = 0.05))),
                priorSD = HalfT(scale = 0.1),
                lower = 0.0001,
                upper = 0.4,
                jump = 0.045)

struc_zero_internal <- Values(array(c(rep(0L, 16),
                                      c(0L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L)),
                                    dim = c(4, 4, 2),
                                    dimnames = list(status_orig = c("Single", "Married", "Divorced", "Widowed"),
                                                    status_dest = c("Single", "Married", "Divorced", "Widowed"),
                                                    age = c("0-14", "15+"))))
internal <- Model(internal ~ Poisson(mean ~ (age + sex + status_orig + status_dest + time)^2,
                                     structuralZeros = struc_zero_internal),
                  time ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                             trend = Trend(scale = HalfT(scale = 0.1)),
                             damp = NULL,
                             error = Error(scale = HalfT(scale = 0.1))),
                  age:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                 trend = Trend(scale = HalfT(scale = 0.05)),
                                 damp = NULL,
                                 error = Error(scale = HalfT(scale = 0.05))),
                  sex:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                 trend = Trend(scale = HalfT(scale = 0.05)),
                                 damp = NULL,
                                 error = Error(scale = HalfT(scale = 0.05))),
                  status_orig:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                         trend = Trend(scale = HalfT(scale = 0.05)),
                                         damp = NULL,
                                         error = Error(scale = HalfT(scale = 0.05))),
                  status_dest:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                                         trend = Trend(scale = HalfT(scale = 0.05)),
                                         damp = NULL,
                                         error = Error(scale = HalfT(scale = 0.05))),
                  priorSD = HalfT(scale = 0.1),
                  lower = 0.0001,
                  upper = 1,
                  jump = 0.3)

struc_zero_deaths <- Values(array(c(1, 1, 0, 1, 0, 1, 0, 1),
                                  dim = c(2, 4),
                                  dimnames = list(age = c("0-14", "15+"),
                                                  status = c("Single", "Married", "Divorced", "Widowed"))))
deaths <- Model(deaths ~ Poisson(mean ~ age * time + sex,
                                 structuralZeros = struc_zero_deaths),
                age ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                          trend = Trend(scale = HalfT(scale = 0.1)),
                          damp = NULL,
                          error = Error(scale = HalfT(scale = 0.1))),
                time ~ DLM(level = Level(scale = HalfT(scale = 0.1)),
                           trend = Trend(scale = HalfT(scale = 0.1)),
                           damp = NULL,
                           error = Error(scale = HalfT(scale = 0.1))),
                age:time ~ DLM(level = Level(scale = HalfT(scale = 0.05)),
                               trend = Trend(scale = HalfT(scale = 0.05)),
                               damp = NULL,
                               error = Error(scale = HalfT(scale = 0.05))),
                priorSD = HalfT(scale = 0.1),
                lower = 0.0001,
                upper = 0.1,
                jump = 0.2)



system_models <- list(population,
                      births,
                      internal,
                      deaths)

saveRDS(system_models,
        file = "out/system_models.rds")

